dataset:
  _target_: nos.data.transmission_loss.TLDatasetCompact
  path:
    _target_: pathlib.Path
    _args_:
      - data/smooth.csv

training:
  epochs: 500
  lr: 1e-3
  start_seed: 0
  end_seed: 5

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +operator: deep_cat_operator