dataset:
  _target_: nos.data.transmission_loss.TLDatasetCompact
  path:
    _target_: pathlib.Path
    _args_:
      - data/smooth.csv

training:
  epochs: [200, 1000]
  lr: [1e-4, 1e-3]
  batch_size: [1, 32]

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +operator: encoded_fourier_neural_operator, deep_neural_operator, deep_cat_operator, deep_o_net