dataset:
  _target_: nos.data.transmission_loss.TLDatasetCompact
  path:
    _target_: pathlib.Path
    _args_:
      - data/smooth.csv

training:
  batch_size: [1, 32]

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +operator: deep_o_net, deep_neural_operator, deep_cat_operator, encoded_fourier_neural_operator