architecture:
  _target_: continuiti.operators.deep_cat_operator.DeepCatOperator
  branch_width: 16
  branch_depth: 4
  trunk_width: 16
  trunk_depth: 4
  cat_net_width: 16
  cat_net_depth: 4

hyperparameter:
  batch_size: 20
