architecture:
  _target_: continuiti.operators.deeponet.DeepONet

parameter_space:
  branch_width: [16, 96]
  branch_depth: [4, 64]
  branch_width: [16, 96]
  branch_depth: [4, 64]
  basis_functions: [4, 96]
