architecture:
  _target_: continuiti.operators.deep_cat_operator.DeepCatOperator

parameter_space:
  branch_width: [32, 64]
  branch_depth: [4, 16]
  trunk_width: [32, 64]
  trunk_depth: [4, 16]
  cat_net_width: [32, 64]
  cat_net_depth: [16, 32]
